### PR TITLE
Feature/15 add hardcoded response data

### LINKED ISSUE #15: Add hardcoded response data
At the moment the paperlessREST server is just returning empty responses. 
It should return hard coded dummy data to mimic the functionality of a "true" working endpoint.

In the screenshot the missing endpoints are visible:

Screenshot from 2023-11-02 18-29-52

- GET /api/saved_views/
  - just add hardcoded response

- POST /api/ui_settings/
  - CORS problem? --> allow CORS on request

- GET /api/tasks/
  - Generate APIs once again --> we are missing it
  - Add hardcoded response

- GET /api/statistics/
  - Generate APIs once again --> we are missing it
  - Add hardcoded response

### PR DESCRIPTION
**Pull request by skyler544**
This pull request should close #15 by ensuring that:
1. All endpoints used by the Paperless UI exist in the backend
2. All endpoints used by the Paperless UI return at the very least a `200`

### CODE REVIEW

**Comment by skyler544** [comment]
As of d4a1cb0 the only endpoints still failing are `POST /api/ui_settings/` and `GET /ws/status/`

- `POST /api/ui_settings/` seems to be failing because the Paperless UI doesn't actually send all of the required parameters (for now). I think this may be safely ignored?
- `GET /ws/status` seems to be trying to communicate with port `8000`. Why?

**Comment by juliusBam** [comment]
> As of [d4a1cb0](https://github.com/Grossstadt-Pinguine/SWKOM_Paperless/commit/d4a1cb0e12b8a3759aeda55f5bacb06d58fd8015) the only endpoints still failing are `POST /api/ui_settings/` and `GET /ws/status/`
> 
>     * `POST /api/ui_settings/` seems to be failing because the Paperless UI doesn't actually send all of the required parameters (for now). I think this may be safely ignored?
> 
>     * `GET /ws/status` seems to be trying to communicate with port `8000`. Why?
> 
> 
> 2023-11-03_678x201

I also think the error for `POST /api/ui_settings/` can be safely ignored for the time being, it probably takes the parameters from some response were we return empty data.

Maybe the requests `GET /ws/status` uses the port 8000 because it is not included in the proxy?

**Review by juliusBam — APPROVED** [review]

**Review by juliusBam — APPROVED** [review]
Even if the mentioned endpoints still do not work (see comment https://github.com/Grossstadt-Pinguine/SWKOM_Paperless/pull/16#issuecomment-1792496405) the project should still be fine.
Good job!

**Review by Pe-Ga — APPROVED** [review]
Gr8 !

**Pull request merged**
